databases:
  - name: mini_capstone_api
    plan: free
    databaseName: mini_capstone_api
    user: mini_capstone_api

services:
  - type: web
    plan: free
    name: mini_capstone_api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mini_capstone_api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
